version: '3.8'

services:
  db:
    image: postgres:17-alpine
    ports:
      - 5433:5432
    environment:
      - POSTGRES_DB=excrud
      - POSTGRES_USER=exroot
      - POSTGRES_PASSWORD=expass
    volumes:
      - pg_books_store:/var/lib/postgresql/data
    restart: unless-stopped

  api:
    build: .
    environment:
      - DATABASE_URL=postgresql://exroot:expass@db:5432/excrud?schema=SCHEMA
      - HOST=0.0.0.0
      - PORT=7771
      - PRIVATE_KEY=MYPRIVATEKEY
    ports:
      - 5434:7771
    depends_on:
      - db
    restart: unless-stopped

volumes:
  pg_books_store:
